In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

GET DATA

In [2]:
a=np.arange(15).reshape(-1,1)
b=np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1])


In [4]:
a,b


(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]]), array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]))

In [11]:
#creating and training model
model = LogisticRegression(C=0.75)
model.fit(a,b)

LogisticRegression(C=0.75)

In [12]:
#attributes of the model
model.classes_

array([0, 1])

In [13]:
#calculating the intercept
model.intercept_

array([-6.55661546])

In [14]:
#calculating or estimating co_efficient
model.coef_

array([[0.87404936]])

In [16]:
#evaluating he model (probability)
model.predict_proba(a)

array([[0.99858133, 0.00141867],
       [0.99660674, 0.00339326],
       [0.99190609, 0.00809391],
       [0.98081899, 0.01918101],
       [0.95523018, 0.04476982],
       [0.89901872, 0.10098128],
       [0.787901  , 0.212099  ],
       [0.60784672, 0.39215328],
       [0.39274711, 0.60725289],
       [0.2125155 , 0.7874845 ],
       [0.10120761, 0.89879239],
       [0.04487645, 0.95512355],
       [0.01922792, 0.98077208],
       [0.00811393, 0.99188607],
       [0.00340169, 0.99659831]])

In [17]:
#getting actual predictions
y_pred = model.predict(a)
print(y_pred)

[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]


In [18]:
#predicting accuracy
model.score(a,b)

0.8666666666666667

In [25]:
#building confusion matrix
confusion_matrix(b, y_pred)

array([[7, 1],
       [1, 6]])

In [28]:
#more comprehensive report on the classification 
print(classification_report(b, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88         8
           1       0.86      0.86      0.86         7

    accuracy                           0.87        15
   macro avg       0.87      0.87      0.87        15
weighted avg       0.87      0.87      0.87        15

