In [4]:
#importing the packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits


In [5]:
#get data directly from scikit-learn
X, y = load_digits(return_X_y=True)

In [6]:
X.shape , y.shape

((1797, 64), (1797,))

In [19]:
X[0], y[0]

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]), 0)

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.5,random_state=0)

In [21]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])
     

(array([ 0.,  0.,  1., 12., 10.,  3.,  0.,  0.,  0.,  0.,  7., 16., 16.,
         7.,  0.,  0.,  0.,  0., 12., 16., 16.,  3.,  0.,  0.,  0.,  0.,
        14., 16., 16.,  2.,  0.,  0.,  0.,  1., 15., 16., 16.,  5.,  0.,
         0.,  0.,  0., 15., 16., 15.,  2.,  0.,  0.,  0.,  0., 11., 16.,
        16.,  8.,  0.,  0.,  0.,  0.,  1.,  7., 12., 10.,  0.,  0.]),
 5.453125,
 6.616574093469747)

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
     

In [23]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([ 0.        , -0.33909743, -0.84688888,  0.05482959, -0.43816862,
        -0.48004253, -0.38979278, -0.13222862, -0.06318997, -0.61627349,
        -0.58641731,  0.96491198,  1.16387138, -0.19972684, -0.51999189,
        -0.12765957, -0.03338903, -0.70342101,  0.40501097,  1.53361441,
         1.41715732, -0.79435104, -0.56567674, -0.11762525, -0.03338903,
        -0.78238272,  0.7949161 ,  1.25272389,  0.98452445, -0.9497941 ,
        -0.65670643, -0.03338903,  0.        , -0.40563056,  1.13807573,
         1.06836806,  0.93362032, -0.62827871, -0.83019095,  0.        ,
        -0.06607232, -0.5375342 ,  1.19757009,  1.29965899,  1.13135421,
        -1.08452686, -0.75016027, -0.10348465, -0.0503716 , -0.41044865,
         0.5995096 ,  1.20560823,  1.22857215, -0.08867082, -0.71289013,
        -0.20692566, -0.03338903, -0.3004699 , -0.86146763, -1.12213945,
         0.05360588,  0.60060782, -0.48879987, -0.17724876]),
 0.011872013072994958,
 0.7250331346605874)

In [24]:
#create a model and train it
model = LogisticRegression(C=0.05, multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0)

In [25]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [26]:
model.score(X_train, y_train)

0.9743875278396437

In [27]:
confusion_matrix(y_test,y_pred)

array([[ 89,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  83,   1,   0,   1,   0,   1,   0,   1,   3],
       [  0,   1,  89,   0,   0,   0,   0,   2,   0,   0],
       [  0,   0,   1,  86,   0,   1,   0,   2,   2,   1],
       [  0,   0,   0,   0,  73,   0,   0,   2,   1,   0],
       [  0,   0,   0,   0,   0, 103,   1,   0,   0,   4],
       [  0,   1,   0,   0,   1,   0,  87,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  78,   0,   0],
       [  0,   3,   2,   2,   0,   2,   1,   0,  78,   4],
       [  0,   0,   0,   2,   0,   2,   0,   2,   2,  84]])

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        89
           1       0.94      0.92      0.93        90
           2       0.96      0.97      0.96        92
           3       0.96      0.92      0.94        93
           4       0.97      0.96      0.97        76
           5       0.95      0.95      0.95       108
           6       0.97      0.98      0.97        89
           7       0.91      1.00      0.95        78
           8       0.93      0.85      0.89        92
           9       0.88      0.91      0.89        92

    accuracy                           0.95       899
   macro avg       0.95      0.95      0.95       899
weighted avg       0.95      0.95      0.95       899

